import {
  Code,
  Database,
  Brain,
  Layout,
  Server,
  Smartphone,
  Globe,
  Settings,
} from "lucide-react"

export const personalInfo = {
  name: "Andressa Silva",
  title: "Desenvolvedora Full Stack",
  subtitle: "Full Stack Developer",
  role: "Desenvolvedora Full Stack & Especialista em IA",
  roleEn: "Full Stack Developer & AI Specialist",
  description:
    "Especializada em Python, Django, React, Angular e tecnologias de IA/ML. Construindo aplicações web inteligentes e escaláveis.",
  descriptionEn:
    "Specialized in Python, Django, React, Angular, and AI/ML technologies. Building intelligent and scalable web applications.",
  social: {
    github: "https://github.com/AndressaSilva0",
    linkedin: "https://www.linkedin.com/in/andressa-silva-29430a218/",
    twitter: "https://www.x.com/saturn_girlxxxx",
    instagram: "https://www.instagram.com/andressa.saturn",
  },
  contact: {
    email: "andressasp68@gmail.com",
    phone: "+55 (99) 99111-6301",
  },
}

export const navItems = [
  { name: "Sobre", href: "#about" },
  { name: "Serviços", href: "#services" },
  { name: "Habilidades", href: "#skills" },
  { name: "Portfólio", href: "#portfolio" },
  { name: "Contato", href: "#contact" },
]

export const services = [
  {
    title: "Desenvolvimento Full Stack",
    icon: Code,
    description: "Construindo aplicações web completas com Django, React, Angular e Node.js.",
    features: [
      "Desenvolvimento Frontend Responsivo",
      "APIs RESTful e GraphQL",
      "Bancos de Dados SQL e NoSQL",
      "Autenticação e Autorização",
    ],
  },
  {
    title: "IA & Machine Learning",
    icon: Brain,
    description: "Desenvolvendo aplicações inteligentes com machine learning, deep learning e NLP.",
    features: [
      "Modelos de Machine Learning",
      "Processamento de Linguagem Natural",
      "Integração com LLMs",
      "Análise Preditiva",
    ],
  },
  {
    title: "Ciência de Dados & Análises",
    icon: Database,
    description: "Transformando dados em insights acionáveis para inteligência de negócios.",
    features: [
      "Visualização de Dados",
      "ETL e Processamento de Dados",
      "Dashboards Interativos",
      "Relatórios Automatizados",
    ],
  },
]

export const skills = {
  technical: [
    { name: "Python", icon: "/python.png" },
    { name: "React", icon: "/react.svg" },
    { name: "Docker", icon: "/docker.svg" },
    { name: "PHP", icon: "/php.svg" },
    { name: "Laravel", icon: "/laravel.svg" },
    { name: "MySQL", icon: "/mysql.svg" },
    { name: "PostgreSQL", icon: "/postgresql.svg" },
    { name: "Django", icon: "/django.png" },
    { name: "Angular", icon: "/angular.png" },
    { name: "Node.js", icon: "/node.png" },
    { name: "TypeScript", icon: "/typescript.png" },
    { name: "JavaScript", icon: "/javascript.png" },
    { name: "HTML", icon: "/html.png" },
    { name: "CSS", icon: "/css.png" },
    { name: "SQLite", icon: "/sqlite.png" },
  ],
  areas: [
    { name: "Desenvolvimento Frontend", icon: Layout },
    { name: "Desenvolvimento Backend", icon: Server },
    { name: "Bancos de Dados", icon: Database },
    { name: "DevOps", icon: Settings },
    { name: "UI/UX Design", icon: Smartphone },
    { name: "Inteligência Artificial", icon: Brain },
    { name: "Ciência de Dados", icon: Database },
    { name: "APIs RESTful", icon: Globe },
  ],
  languages: [
    { name: "Português", level: "Fluente", percent: 100 },
    { name: "Francês", level: "Avançado", percent: 85 },
    { name: "Inglês", level: "Intermediário", percent: 60 },
    { name: "Espanhol", level: "Intermediário", percent: 60 },
  ],
}

export const projects = [
  {
    id: 1,
    title: "FEMAQUA",
    tech: "PHP",
    category: "web",
    description: "Ferramentas Maravilhosas Que Adoro",
    descriptionEn: "Wonderful Tools I Love",
    image: "/femaqua.png",
    githubUrl: "https://github.com/AndressaSilva0/femaqua",
  },
  {
    id: 17,
    title: "Damas Tech API",
    tech: "Laravel • PHP • Docker",
    category: "web",
    description: "Plataforma de educação, comunidade e empregabilidade para mulheres na tecnologia.",
    descriptionEn: "Education, community, and employability platform for women in tech.",
    image: "/damas-tech.png",
    githubUrl: "https://github.com/Damas-Tech/api_damas_tech",
  },
  {
    id: 2,
    title: "API Travel Agent",
    tech: "Python",
    category: "ai",
    description: "API para o agente de viagens inteligente",
    descriptionEn: "API for the intelligent travel agent",
    image: "/api-travel.png",
    githubUrl: "https://github.com/AndressaSilva0/api_travel_agent",
  },
  {
    id: 3,
    title: "Page Agente Viagens",
    titleEn: "Travel Agent Page",
    tech: "TypeScript",
    category: "web",
    description: "Frontend para o sistema de agente de viagens",
    descriptionEn: "Frontend for the travel agent system",
    image: "/travel-agent-page.png",
    githubUrl: "https://github.com/AndressaSilva0/page-agente-viagens",
  },
  {
    id: 4,
    title: "Travel Agent",
    tech: "Python",
    category: "ai",
    description: "Sistema de agente de viagens com IA",
    descriptionEn: "AI-powered travel agent system",
    image: "/travel-agent-ai.png",
    githubUrl: "https://github.com/AndressaSilva0/travel-agent",
  },
  {
    id: 5,
    title: "Gerenciador de Assinaturas",
    titleEn: "Subscription Manager",
    tech: "Python",
    category: "web",
    description: "Sistema para gerenciamento de assinaturas recorrentes",
    descriptionEn: "System for managing recurring subscriptions",
    image: "/subscription-manager.png",
    githubUrl: "https://github.com/AndressaSilva0/gerenciador-de-assinaturas",
  },
  {
    id: 6,
    title: "Biblio Frontend",
    tech: "JavaScript",
    category: "web",
    description: "Frontend para sistema de biblioteca",
    descriptionEn: "Frontend for library system",
    image: "/biblio-frontend.png",
    githubUrl: "https://github.com/AndressaSilva0/biblio-frontend",
  },
  {
    id: 7,
    title: "Biblio Backend",
    tech: "Python",
    category: "web",
    description: "Backend para sistema de biblioteca",
    descriptionEn: "Backend for library system",
    image: "/biblio-backend.png",
    githubUrl: "https://github.com/AndressaSilva0/backend-biblio",
  },
  {
    id: 8,
    title: "Análise de Dados dos Pokémons",
    titleEn: "Pokémon Data Analysis",
    tech: "Jupyter Notebook",
    category: "data",
    description: "Análise estatística de dados de Pokémons",
    descriptionEn: "Statistical analysis of Pokémon data",
    image: "/pokemon-data.png",
    githubUrl: "https://github.com/AndressaSilva0/analise_de_dados_dos_pokemons",
  },
  {
    id: 9,
    title: "Pokedex",
    tech: "JavaScript/CSS",
    category: "web",
    description: "Projeto criado a partir da PokeApi",
    descriptionEn: "Project created using PokeApi",
    image: "/pokedex.png",
    githubUrl: "https://github.com/AndressaSilva0/Pokedex",
  },
  {
    id: 10,
    title: "Buzzfeed Quiz Clone",
    tech: "Angular",
    category: "web",
    description: "Quiz inspirado no Buzzfeed feito com Angular",
    descriptionEn: "Buzzfeed-inspired quiz made with Angular",
    image: "/buzzfeed-quiz.png",
    githubUrl: "https://github.com/AndressaSilva0/buzzfeed-quiz-clone",
  },
  {
    id: 11,
    title: "Angular Blog",
    tech: "Angular",
    category: "web",
    description: "Blog desenvolvido em Angular",
    descriptionEn: "Blog developed in Angular",
    image: "/angular-blog.png",
    githubUrl: "https://github.com/AndressaSilva0/angular-blog",
  },
  {
    id: 12,
    title: "Estrutura de Dados em C",
    titleEn: "Data Structures in C",
    tech: "C",
    category: "cs",
    description: "Estudos e implementações de estruturas de dados",
    descriptionEn: "Studies and implementations of data structures",
    image: "/c-structures.png",
    githubUrl: "https://github.com/AndressaSilva0/Estrutura-de-Dados-em-Linguagem-C",
  },
  {
    id: 13,
    title: "Exercícios Cap 6 Manzano",
    titleEn: "Manzano Exercises Cap 6",
    tech: "C",
    category: "cs",
    description: "Resolução de exercícios de lógica e algoritmos",
    descriptionEn: "Resolution of logic and algorithm exercises",
    image: "/manzano-6.png",
    githubUrl: "https://github.com/AndressaSilva0/exercicios-capitulo-6-manzano",
  },
  {
    id: 14,
    title: "Exercícios Cap 5 Manzano",
    titleEn: "Manzano Exercises Cap 5",
    tech: "C",
    category: "cs",
    description: "Resolução de exercícios de lógica e algoritmos",
    descriptionEn: "Resolution of logic and algorithm exercises",
    image: "/manzano-5.png",
    githubUrl: "https://github.com/AndressaSilva0/Exerc-cio-cap-tulo-5-Manzano",
  },
  {
    id: 15,
    title: "Desafio Leetcode",
    titleEn: "Leetcode Challenge",
    tech: "JavaScript",
    category: "cs",
    description: "Soluções para desafios do Leetcode",
    descriptionEn: "Solutions for Leetcode challenges",
    image: "/leetcode.png",
    githubUrl: "https://github.com/AndressaSilva0/Desafio-Leetcode",
  },
  {
    id: 16,
    title: "7DaysOfCode Lógica JS",
    titleEn: "7DaysOfCode JS Logic",
    tech: "JavaScript",
    category: "cs",
    description: "Desafios de lógica de programação da Alura",
    descriptionEn: "Programming logic challenges from Alura",
    image: "/7days.png",
    githubUrl: "https://github.com/AndressaSilva0/-7DaysOfCode-Logica-JS--Desafio-Alura",
  },
]
